spring:
  application:
    name: ao-gateway-zuul
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
